// Sample JAX Beach data for Phase 0 reference compositions only.
// Venue names and artist names are fictional — invented to read like
// JAX Beach without invoking any real business by name. Photographs are
// brand-palette SVG placeholders generated per card rather than stock
// imagery, so nothing here depends on a CDN or licensed asset.

export type SampleEvent = {
  id: string
  slug: string
  title: string
  artist: string
  venue: string
  neighborhood: string
  startsAt: string
  doorsAt: string
  distanceMiles: number
  status: 'active' | 'confirmed' | 'proposed'
  bucket: 'tonight' | 'tomorrow' | 'weekend'
  palette: 'teal' | 'yellow' | 'coral' | 'orange'
  blurb: string
}

export const SAMPLE_EVENTS: SampleEvent[] = [
  {
    id: 'evt-001',
    slug: 'driftwood-three-sand-dollar',
    title: 'The Driftwood Three',
    artist: 'The Driftwood Three',
    venue: 'Sand Dollar Stage',
    neighborhood: 'Jax Beach',
    startsAt: '2026-06-09T20:30:00-04:00',
    doorsAt: '2026-06-09T19:30:00-04:00',
    distanceMiles: 0.3,
    status: 'active',
    bucket: 'tonight',
    palette: 'coral',
    blurb: 'Three-piece beach folk. First set covers, second set originals.',
  },
  {
    id: 'evt-002',
    slug: 'mara-lyon-pelican-porch',
    title: 'Mara Lyon Quartet',
    artist: 'Mara Lyon Quartet',
    venue: 'Pelican Porch',
    neighborhood: 'Neptune Beach',
    startsAt: '2026-06-09T21:00:00-04:00',
    doorsAt: '2026-06-09T20:00:00-04:00',
    distanceMiles: 0.8,
    status: 'active',
    bucket: 'tonight',
    palette: 'teal',
    blurb: 'Slow blues. Sliding-scale tip jar, no cover.',
  },
  {
    id: 'evt-003',
    slug: 'hank-aiken-pier-six',
    title: 'Hank Aiken & The Sandlines',
    artist: 'Hank Aiken & The Sandlines',
    venue: 'Pier Six Hall',
    neighborhood: 'Jax Beach',
    startsAt: '2026-06-09T22:00:00-04:00',
    doorsAt: '2026-06-09T21:00:00-04:00',
    distanceMiles: 1.1,
    status: 'confirmed',
    bucket: 'tonight',
    palette: 'yellow',
    blurb: 'Roots rock. Standing room.',
  },
  {
    id: 'evt-004',
    slug: 'coco-reyes-salt-surf',
    title: 'Coco Reyes Trio',
    artist: 'Coco Reyes Trio',
    venue: 'Salt & Surf Tap',
    neighborhood: 'Atlantic Beach',
    startsAt: '2026-06-09T19:00:00-04:00',
    doorsAt: '2026-06-09T18:00:00-04:00',
    distanceMiles: 1.6,
    status: 'confirmed',
    bucket: 'tonight',
    palette: 'orange',
    blurb: 'Bossa + samba. Early set, family friendly.',
  },
  // Tomorrow
  {
    id: 'evt-005',
    slug: 'lupita-jane-sand-dollar',
    title: 'Lupita Jane',
    artist: 'Lupita Jane',
    venue: 'Sand Dollar Stage',
    neighborhood: 'Jax Beach',
    startsAt: '2026-06-10T20:00:00-04:00',
    doorsAt: '2026-06-10T19:00:00-04:00',
    distanceMiles: 0.3,
    status: 'confirmed',
    bucket: 'tomorrow',
    palette: 'coral',
    blurb: 'Solo singer-songwriter. Acoustic.',
  },
  {
    id: 'evt-006',
    slug: 'theo-stone-pier-six',
    title: 'Theo Stone Band',
    artist: 'Theo Stone Band',
    venue: 'Pier Six Hall',
    neighborhood: 'Jax Beach',
    startsAt: '2026-06-10T21:30:00-04:00',
    doorsAt: '2026-06-10T20:30:00-04:00',
    distanceMiles: 1.1,
    status: 'confirmed',
    bucket: 'tomorrow',
    palette: 'teal',
    blurb: 'Funk five-piece with horns.',
  },
  {
    id: 'evt-007',
    slug: 'kelp-forest-pelican',
    title: 'Kelp Forest',
    artist: 'Kelp Forest',
    venue: 'Pelican Porch',
    neighborhood: 'Neptune Beach',
    startsAt: '2026-06-10T22:00:00-04:00',
    doorsAt: '2026-06-10T21:00:00-04:00',
    distanceMiles: 0.8,
    status: 'proposed',
    bucket: 'tomorrow',
    palette: 'yellow',
    blurb: 'Indie-jangle four-piece. Album release.',
  },
  {
    id: 'evt-008',
    slug: 'sand-fly-salt-surf',
    title: 'Sand Fly DJ Set',
    artist: 'DJ Sand Fly',
    venue: 'Salt & Surf Tap',
    neighborhood: 'Atlantic Beach',
    startsAt: '2026-06-10T23:00:00-04:00',
    doorsAt: '2026-06-10T22:00:00-04:00',
    distanceMiles: 1.6,
    status: 'confirmed',
    bucket: 'tomorrow',
    palette: 'orange',
    blurb: 'Boogie + Afro-disco vinyl set.',
  },
  // Weekend
  {
    id: 'evt-009',
    slug: 'the-marlins-pier-six',
    title: 'The Marlins',
    artist: 'The Marlins',
    venue: 'Pier Six Hall',
    neighborhood: 'Jax Beach',
    startsAt: '2026-06-13T21:00:00-04:00',
    doorsAt: '2026-06-13T20:00:00-04:00',
    distanceMiles: 1.1,
    status: 'confirmed',
    bucket: 'weekend',
    palette: 'coral',
    blurb: 'Six-piece big-band swing.',
  },
  {
    id: 'evt-010',
    slug: 'rita-ortiz-sand-dollar',
    title: 'Rita Ortiz Quintet',
    artist: 'Rita Ortiz Quintet',
    venue: 'Sand Dollar Stage',
    neighborhood: 'Jax Beach',
    startsAt: '2026-06-13T22:00:00-04:00',
    doorsAt: '2026-06-13T21:00:00-04:00',
    distanceMiles: 0.3,
    status: 'confirmed',
    bucket: 'weekend',
    palette: 'teal',
    blurb: 'Latin jazz. Reservations recommended.',
  },
  {
    id: 'evt-011',
    slug: 'oakwood-ramblers-pelican',
    title: 'Oakwood Ramblers',
    artist: 'Oakwood Ramblers',
    venue: 'Pelican Porch',
    neighborhood: 'Neptune Beach',
    startsAt: '2026-06-14T19:30:00-04:00',
    doorsAt: '2026-06-14T18:30:00-04:00',
    distanceMiles: 0.8,
    status: 'confirmed',
    bucket: 'weekend',
    palette: 'yellow',
    blurb: 'Bluegrass quintet. Outdoor stage.',
  },
  {
    id: 'evt-012',
    slug: 'low-tide-revival-salt-surf',
    title: 'Low Tide Revival',
    artist: 'Low Tide Revival',
    venue: 'Salt & Surf Tap',
    neighborhood: 'Atlantic Beach',
    startsAt: '2026-06-14T20:00:00-04:00',
    doorsAt: '2026-06-14T19:00:00-04:00',
    distanceMiles: 1.6,
    status: 'proposed',
    bucket: 'weekend',
    palette: 'orange',
    blurb: 'Surf-rock + reggae. Free, 21+.',
  },
  {
    id: 'evt-013',
    slug: 'the-driftwood-three-encore',
    title: 'The Driftwood Three (encore)',
    artist: 'The Driftwood Three',
    venue: 'Sand Dollar Stage',
    neighborhood: 'Jax Beach',
    startsAt: '2026-06-14T22:00:00-04:00',
    doorsAt: '2026-06-14T21:00:00-04:00',
    distanceMiles: 0.3,
    status: 'confirmed',
    bucket: 'weekend',
    palette: 'coral',
    blurb: 'Late set, originals only.',
  },
  {
    id: 'evt-014',
    slug: 'mara-lyon-pelican-encore',
    title: 'Mara Lyon Quartet',
    artist: 'Mara Lyon Quartet',
    venue: 'Pelican Porch',
    neighborhood: 'Neptune Beach',
    startsAt: '2026-06-13T20:00:00-04:00',
    doorsAt: '2026-06-13T19:00:00-04:00',
    distanceMiles: 0.8,
    status: 'confirmed',
    bucket: 'weekend',
    palette: 'teal',
    blurb: 'Saturday residency, week 4.',
  },
  {
    id: 'evt-015',
    slug: 'theo-stone-pier-six-encore',
    title: 'Theo Stone Band',
    artist: 'Theo Stone Band',
    venue: 'Pier Six Hall',
    neighborhood: 'Jax Beach',
    startsAt: '2026-06-14T21:30:00-04:00',
    doorsAt: '2026-06-14T20:30:00-04:00',
    distanceMiles: 1.1,
    status: 'confirmed',
    bucket: 'weekend',
    palette: 'yellow',
    blurb: 'Sunday-night funk. Six-week residency.',
  },
  {
    id: 'evt-016',
    slug: 'dj-sand-fly-salt-surf-encore',
    title: 'DJ Sand Fly',
    artist: 'DJ Sand Fly',
    venue: 'Salt & Surf Tap',
    neighborhood: 'Atlantic Beach',
    startsAt: '2026-06-13T23:00:00-04:00',
    doorsAt: '2026-06-13T22:00:00-04:00',
    distanceMiles: 1.6,
    status: 'confirmed',
    bucket: 'weekend',
    palette: 'orange',
    blurb: 'Late-night boogie. Free.',
  },
]

export function eventsInBucket(bucket: SampleEvent['bucket']) {
  return SAMPLE_EVENTS.filter((e) => e.bucket === bucket)
}
